[project]
authors = ["OxiSwap"]
entry = "main.sw"
license = "Apache-2.0"
name = "crypto-pairs"

[dependencies]
sway_libs = { git = "https://github.com/FuelLabs/sway-libs", tag = "v0.24.0" }
libraries = { path = "../libraries" }
standards = { git = "https://github.com/FuelLabs/sway-standards", tag = "v0.6.1" }